### ISSUE TITLE
[Ports]: Backport client side changes

### ISSUE THREAD

**Issue by playwrightmachine** [microsoft/playwright-java#1037]
Please backport client side changes:
  - [x] https://github.com/microsoft/playwright/commit/622c73cc1e677834ebdc27e95c89ff101bdccf54 (feat: expect(locator).toHaveAttribute to assert attribute presence (#16767))
  - [x] https://github.com/microsoft/playwright/commit/a07a4a25a26e2fa6a976fb2ff174f25b24414da6 (chore: make parent scope explicit (#16819))
  - [x] https://github.com/microsoft/playwright/commit/f30ac1d67827fbcf3f8be7a851ef81b761842c52 (fix: support toHaveAttribute(name, options) (#16941))
  - [x] https://github.com/microsoft/playwright/commit/306ab34aa3bcdfbb2369e1c698a161565bacc275 (feat(assertions): support toBeEnabled({ enabled }) (#17058))
  - [x] https://github.com/microsoft/playwright/commit/f0c581060959bf680d2165f38e29743388d03b21 (feat(assertions): support toBeEditable({ editable }) (#17065))
  - [x] https://github.com/microsoft/playwright/commit/c91df61ca33c133046425d40b45dfc25ec331673 (chore: optionally connect instead of launching (#17174))
  - [x] https://github.com/microsoft/playwright/commit/bca13bc35aead0122b0609ea18a0769864616c29 (feat(assertions): support toBeVisible({ visible }) (#17207))
  - [x] https://github.com/microsoft/playwright/commit/17b203affbc373fd5c7d8e643285e1262350cc67 (feat: added follow and redirect arguments to fetch (#17033))
