### ISSUE TITLE
[Ports]: Backport client side changes

### ISSUE THREAD

**Issue by playwrightmachine** [microsoft/playwright-java#1075]
Please backport client side changes:
  - [x] https://github.com/microsoft/playwright/commit/df143031e7eac11460bcd658dc3bb5a8951ccd64 (chore: move protocol and trace types into the top-level packages (#17486))
  - [x] https://github.com/microsoft/playwright/commit/f5d708981957a6f63b6bad17405bfb5cb7eb285b (fix: accept post data params for request.get and request.head (#17566))
  - [x] https://github.com/microsoft/playwright/commit/72a24973f3246c952de918f607ca370443f8d4c3 (fix: ignore timing data when request served from memory cache (#17595))
  - [x] https://github.com/microsoft/playwright/commit/06e73b414f118af2070f978e394c3ad8a2109f49 (chore: move connect utility into localUtils (#17590))
  - [x] https://github.com/microsoft/playwright/commit/d9a28bd2442fdf7c4d46fa07778241851fb53b9c (feat(api): introduce get/getByText/getByRole (#17577))
  - [x] https://github.com/microsoft/playwright/commit/d8f67eb75dab132a3b487b10c2451574515b17a5 (feat(api): introduce getByTestId (#17645))
  - [x] https://github.com/microsoft/playwright/commit/2a85806cc0a903f676036af7f5fab603ac45205e (chore: follow up to getTestById, escape it (#17650))
  - [x] https://github.com/microsoft/playwright/commit/e3a2316013eb8959e3d83ecebd77dea48410c6f5 (feat(api): add getByLabelText (#17684))
  - [x] https://github.com/microsoft/playwright/commit/b4ee84fb0c40c2e4ee0c75062f2d3134fbb5698b (chore(api): remove locator.get() (#17709))
  - [x] https://github.com/microsoft/playwright/commit/083fb4401c4db6dd97cfcf48e238cbba167701ca (feat(api): add getByPlaceholderText (#17722))
  - [x] https://github.com/microsoft/playwright/commit/bfb8a43ece9b5d96e9e0a74a5c7d4f37d38211fe (feat(api): all getByTitle, getByAltText (#17724))
  - [x] https://github.com/microsoft/playwright/commit/8810b55504f768c244d2ca1ecb8e5352d00069e5 (feat(api): shorted getByLabel, getByPlaceholder (#17816))
  - [x] https://github.com/microsoft/playwright/commit/a9c02b975365a1b4e7d15cce5e6136ce42bf24e9 (fix(locators): properly escape various locator methods (#17798))
  - [x] https://github.com/microsoft/playwright/commit/2bcd9ce9ae8eabf25356dfa8f367a68bb6b1e51c (chore: internal selectors (#17827))
  - [x] https://github.com/microsoft/playwright/commit/ff15fcf91189ea91b4557bbee03bca89cb9fc3fe (chore: hide selector factories (#17844))
  - [x] https://github.com/microsoft/playwright/commit/8b018f6b4154782f7dc525e3df94d7374b001880 (chore: make role name case-insensitive (#17888))
  - [x] https://github.com/microsoft/playwright/commit/1b5c2f9aba2221157a572e53c2b2d12181f06dfe (fix(trace): show waitForLoadState when event has already fired (#17826))
