### ISSUE TITLE
[Ports]: Backport client side changes

### ISSUE THREAD

**Issue by playwrightmachine** [microsoft/playwright-java#1101]
Please backport client side changes:
  - [x] https://github.com/microsoft/playwright/commit/64e80f0460d1f4d000d5f9ed7018ea0a8c329a77 (chore: beautify error message (#18002))
  - [x] https://github.com/microsoft/playwright/commit/304a4ee8ec81ec5b80e28ffefa74f60453a02959 (chore: migrate to the internal:text selector (#18135))
  - [x] https://github.com/microsoft/playwright/commit/84daeafb3a850233504bf716b469c9bc636a87e6 (chore: use internal locator for role (#18187))
  - [x] https://github.com/microsoft/playwright/commit/48c44f2c787221523badd666ba25162dc17da4fc (fix(selectors): hasText and getByText exact match should consider full text (#18260))
  - [x] https://github.com/microsoft/playwright/commit/d3948d1308b39406dd2da561da18251ff5369b42 (chore: enable debug controller testing (#18270))
  - [x] https://github.com/microsoft/playwright/commit/805312b7227b10b1bff9cdda9fe4c421fef3b182 (feat(android): add Android.{launchServer,connect} (#18263))
  - [x] https://github.com/microsoft/playwright/commit/329b3eadb4f5a73b8a663a1f41a5302aebb0bff1 (feat: locator.blur() (#18303))
  - [x] https://github.com/microsoft/playwright/commit/0fe1998c72d57d77551abc472ab7ece3d1a98c90 (feat(api): add clear() (#18296))
  - [x] https://github.com/microsoft/playwright/commit/e25537f94193fe74174698f65b66d3bf3586f41d (feat(android): add AndroidDevice.close event (#18306))
  - [x] https://github.com/microsoft/playwright/commit/a7f5f2d7a1dcc231aeb328fb068fb4ce68dc000d (chore: allow not overriding media when creating context (#18413))
  - [x] https://github.com/microsoft/playwright/commit/8538f61a72a53c672231cbddc3cbdd3ab248535a (feat(containers): implement global network tethering for playwright server (#17719))
  - [x] https://github.com/microsoft/playwright/commit/8432d1592fc17ee2254cf4c012256897fa589830 (chore: expose new locator apis on window.playwright (#18595))
  - [x] https://github.com/microsoft/playwright/commit/0355d8618fb1c8cb3bc7479fb8f93f0372df7836 (chore: use provided value for the generated test id (#18631))
  - [x] https://github.com/microsoft/playwright/commit/c25e67a0e797887c589f1bf02c953700623fde61 (chore: conditionally dispatch network events (#18687))
  - [x] https://github.com/microsoft/playwright/commit/7c80b77c57881e9fdd7f7c504877a9a11e589b03 (feat(clear): remove `clear()` methods from all classes except `Locator` (#18703))
  - [x] https://github.com/microsoft/playwright/pull/18719/files#diff-7567c52473570e6a6bbfe39c7651e5d1b76514c579021b8c21fc5d781bcfd3d7R76 and https://github.com/microsoft/playwright/pull/18719/files#diff-1a642d60eddb0cd8576a4ece567a68de94afb12170c3f50c78da15696eec9b38R148
