### ISSUE TITLE
[Ports]: Backport client side changes

### ISSUE THREAD

**Issue by playwrightmachine** [microsoft/playwright-java#1407]
Please backport client side changes:
  - [x] https://github.com/microsoft/playwright/commit/f212fd1a8318345147c7357ced36db21acd477a0 (chore: unify target closed errors (#27540))
  - [x] https://github.com/microsoft/playwright/commit/f8a30fb726bc35d4058a2d010b2ed5f6ca2409a3 (chore: follow up to target close message)
  - [x] https://github.com/microsoft/playwright/commit/4e845e7b1dc1f18511eae105e6dea9cce942bd28 (fix(fetch): JSON.stringify on client (#27644))
  - [x] https://github.com/microsoft/playwright/commit/a54dbfdadf82d5bc201f816a419604557a207611 (chore: plumb the target close reason when test fails (#27640))
  - [x] https://github.com/microsoft/playwright/commit/d4296dbff45d80b210f97a6718051800b5d846f2 (chore: break dowload.path() to throw (#27662))
  - [x] https://github.com/microsoft/playwright/commit/091f6883f5524c876022c77b4fdc52b583b4c7cb (chore: remove the usages of raw target closed message constant (#27669))
  - [x] https://github.com/microsoft/playwright/commit/3aa147914c5eafdf5a4ecc61d791e4a7deb920d4 (chore: split error to client and server sides (#27672))
  - [x] https://github.com/microsoft/playwright/commit/bd58c0d5d2f459f5c8ed1e370de8a4ce458a5c91 (fix: preserve lastModified timestamp in setInputFiles (#27671))
  - [x] https://github.com/microsoft/playwright/commit/6fe31ab52c39aa7176c673215caa7a6437d996e9 (feat: support alternative quotes in js parseLocator() (#27718))
  - [x] https://github.com/microsoft/playwright/commit/f48861ddeeb3ea7d46e485836c7320980c537bdd (fix(inspector): highlight xpath/css locators without engine prefix (#27742))
  - [x] https://github.com/microsoft/playwright/commit/7de0ccd36e5ed796ef1cb866d07a17fea57df746 (chore: support await using for close() and dispose() (#27766))
  - [x] https://github.com/microsoft/playwright/commit/0ade5aa9adac16112d82c5ca522ab9abcad6d166 (fix: ignoreCase in toHaveAttribute (#27809))
  - [x] https://github.com/microsoft/playwright/commit/88f30d1ce2e67b569c7110e3ecd000319f92ea28 (feat: support firefoxUserPrefs in launchPersistentContext (#27840))
  - [x] https://github.com/microsoft/playwright/commit/100d3b260171746cf6012a035535731c08ce19f0 (fix(css parser): support nested builtin functions (#27841))
  - [x] https://github.com/microsoft/playwright/commit/59b8cf008e0f3e98936cfeb7776d0a0eda4b22da (fix(codegen): don't generate page.frame() calls anymore (#27820))
  - [x] https://github.com/microsoft/playwright/commit/36c4c24f8a2e073737ae1a0ae4aa5cb42186b669 (fix: only convert input files for browser collocated with server (#27873))
  - [x] https://github.com/microsoft/playwright/commit/5f527fedb1f6893219b69d735b1a9cdd81ad1466 (fix: JSHandle preview text for non-ascii attributes/children (#28038))
  - [x] https://github.com/microsoft/playwright/commit/62b6af3a7f67b08e6588699a49753b7ed3f1e3df (fix(android): respect recordHar option (#28046))
  - [x] https://github.com/microsoft/playwright/commit/fae5dd898a523d61017a8a263f84dd415ab30e5d (chore: remove from client check if browser is co-located with server (#28071))
  - [x] https://github.com/microsoft/playwright/commit/5488c03d7f508737d65a4a932f06aec93969b6c4 (chore: make `asLocator()` always safe (#28207))
