### ISSUE TITLE
[Ports]: Backport client side changes

### ISSUE THREAD

**Issue by playwrightmachine** [microsoft/playwright-java#1529]
Please backport client side changes:
  - [x] https://github.com/microsoft/playwright/commit/a950a7b86b3977e98ef9f2bcfc90817039e38808 (feat: Support intervals arg for toPass (#30037))
  - [x] https://github.com/microsoft/playwright/commit/1602548c105a9ba83de1f905bcc11f78eb193fc1 (docs(java,csharp): add BrowserContext.backgroundPage(s) (#30200))
  - [x] https://github.com/microsoft/playwright/commit/6d56b453ff03b322be70f90c1079961face257a9 (fix(connect): include websocket close reason in the error message (#30203))
  - [x] https://github.com/microsoft/playwright/commit/8056e5391fea6c63f30377542c003b160550c204 (docs: update context.backgroundPage event examples (#30210))
  - [x] https://github.com/microsoft/playwright/commit/e58a33a0ae2791de83ebde7930fc7d29f4d6fad9 (feat(expect) - add ignoreCase option for toHaveURL (#30192))
  - [x] https://github.com/microsoft/playwright/commit/010bc29a3cbc4b4c9326afc3aa03692fed08e1b0 (chore: harden markdown link validation (#30221))
  - [x] https://github.com/microsoft/playwright/commit/88f2717e877987dc6eb5518e16d98a8ca940604e (docs: hint that popup main request is accessible through BrowserContext (#30249))
  - [x] https://github.com/microsoft/playwright/commit/7ad255301f500c323030c2a67415a013e2cf0c35 (docs: fix C# and python snippets (#30232))
  - [x] https://github.com/microsoft/playwright/commit/56a7adeb8ae316c14cefeddc48d67187b4d28d0e (test: unflake 'should not include trace resources from the previous chunks' test (#30257))
  - [x] https://github.com/microsoft/playwright/commit/73fce8fb985d4aee7e28a090572882a3d1969826 (chore: replace Zones with AsyncLocalStorage (#30381))
  - [x] https://github.com/microsoft/playwright/commit/3bdbe4284e840a6a97c4cce461244cc16c76a2a1 (fix(steps): make expect.toPass and expect.poll step containers (#30389))
  - [x] https://github.com/microsoft/playwright/commit/eea1f9984ffa28310df36fbe17f1fefb7e5fb61f (feat: expect(locator).toHaveAccessibleName (#30420))
  - [x] https://github.com/microsoft/playwright/commit/4a275b8ecae906f1859fa0fe0d77fdab6d8bfd4e (feat: expect(locator).toHaveAccessibleDescription (#30463))
  - [x] https://github.com/microsoft/playwright/commit/02c0706896df6285bba98ace433e589095aabb27 (docs: do not recommend waitForLoadState (#30483))
  - [x] https://github.com/microsoft/playwright/commit/230a8437d3745629b643dccac605513138a53317 (feat(fetch): support FormData as multipart parameter (#30489))
  - [x] https://github.com/microsoft/playwright/commit/8fc7723f2209d114811817922105d6e45d91e6ed (fix(types): allow any return type from event handlers (#30492))
  - [x] https://github.com/microsoft/playwright/commit/e2f7acea1e76cbcb1d957e8887dcdde9edd51f14 (docs: fix capitalization and alphabetic order in TestConfig (#30523))
  - [x] https://github.com/microsoft/playwright/commit/59689c9c97a140de2c0bf8a615b53a9e5859961b (feat(addLocatorHandler): various improvements (#30494))
  - [x] https://github.com/microsoft/playwright/commit/9bd2aea13045dbae9ffc6ffa1f8c6a54b5f1091d (feat(locator handler): address api review feedback (#30554))
  - [x] https://github.com/microsoft/playwright/commit/6d20da568e8123dc657abeffce8714af861b89f1 (feat: expect(locator).toHaveRole(role) (#30555))
  - [x] https://github.com/microsoft/playwright/commit/ae9345d0bdd055f34b9738ebc18c47da94c49778 (docs: add FormData to the examples (#30557))
  - [x] https://github.com/microsoft/playwright/commit/1f63cbff08a11f6fad671824adfd4a0f283da29a (docs: toHaveUrl.ignoreCase in languages (#30573))
  - [x] https://github.com/microsoft/playwright/commit/ebafb950542c334147c642cf10d5b6077b58f61e (docs(python): fix CDPSession documentation example (#30584))
  - [x] https://github.com/microsoft/playwright/commit/96f3d19819221f794c4bb720d6d3d0c738f0e48f (feat(ctrl_or_meta): add a universal ctrl-meta modifier (#30572))
  - [x] https://github.com/microsoft/playwright/commit/ff35f651e66913c4ab8fab2fa218da270058fb4b (chore: delete expired location handler from client map (#30574))
  - [ ] https://github.com/microsoft/playwright/commit/d5b387159aa580203753d7a2a533fc9e8ceb7064 (feat(fetch): sendImmediately (#30627))
