### ISSUE TITLE
[Ports]: Backport client side changes for 1.49

### ISSUE THREAD

**Issue by playwrightmachine** [microsoft/playwright-java#1682]
Please backport client side changes:
  - [x] https://github.com/microsoft/playwright/commit/6373fe703dbde7fc40e11a006e48476579664c1a (docs: fix Java/.NET types for docs rolling (#32924))
  - [x] https://github.com/microsoft/playwright/commit/895be9f8de4b1fe06d839370a95ed8464365ac7d (chore: lint java docs snippets (#32945))
  - [x] https://github.com/microsoft/playwright/commit/40670e6ffd579de4c61b6760f606ea90c4cc07cd (fix(emulate media): document "no-preference" as deprecated (#32881))
  - [x] https://github.com/microsoft/playwright/commit/d3fbf1aaeb73ea1c8da448d6f7cb3d318f99c2ed (fix(clock): amend setSystemTime docs (#32901))
  - [x] https://github.com/microsoft/playwright/commit/4fe33db392b075ee302ddb6309b8fd3be5aad2e7 (docs(route): header override propagation (#32971))
  - [x] https://github.com/microsoft/playwright/commit/0f2cbdedacec25bd6894e22055f63c49c43ea208 (fix(routeWebSocket): do not show in the trace (#32991))
  - [x] https://github.com/microsoft/playwright/commit/9fcf60464d983b70b3cafea3e230e4e6e4f92c15 (chore: various v1.48.0 roll fixes for .NET (#33096))
  - [x] https://github.com/microsoft/playwright/commit/a38ff6e0d88008d25e4966373dd2f7c9dabd4d46 (chore: experimental toMatchAriaSnapshot (#33014))
  - [x] https://github.com/microsoft/playwright/commit/8a275e5a5bd6b49d1e7fb8cc330884434375c4ea (docs: improve docs for WebSocketRoute (#33097))
  - [x] https://github.com/microsoft/playwright/commit/4b1fbde2adbfc3d9c9160d2b46671eb0c47c506e (chore: generate match snapshot (#33105))
  - [x] https://github.com/microsoft/playwright/commit/b421bd8b0da0477c13684597e18c811dcfc71519 (chore: add a basic snapshot generator test (#33123))
  - [x] https://github.com/microsoft/playwright/commit/94321fef1c94f9851b6fcc4304d3844760e986cb (chore: implement locator.ariaSnapshot (#33125))
  - [x] https://github.com/microsoft/playwright/commit/0351fd9401a70a6cd300329e7fa1869449cf0a03 (docs: use WebSocketFrame abstraction for Java & .NET (https://github.com/microsoft/playwright/pull/33211))
  - [x] https://github.com/microsoft/playwright/commit/b275c1961237c61492ac6fe20402524cb88d368b (chore: update eslintignore to lint files in utils/ folders (https://github.com/microsoft/playwright/pull/33218))
  - [x] https://github.com/microsoft/playwright/commit/69f56b9f6366858709cb39b5b1054592b029a447 (fix(locator generator): handle `frameLocator()` and `locator().contentFrame()` (https://github.com/microsoft/playwright/pull/33208))
  - [x] https://github.com/microsoft/playwright/commit/a2dec8da63b171b75a32ae66a50336b059c90383 (fix(codegen): SIGINT handling was leading to zombie processes (https://github.com/microsoft/playwright/pull/33269))
  - [x] https://github.com/microsoft/playwright/commit/1e8884621a2a151837fc7d80617b0c5a669013e3 (chore: unify toHaveScreenshot error formatting (https://github.com/microsoft/playwright/pull/33300))
  - [x] https://github.com/microsoft/playwright/commit/c66af9c5250cde23d96751cc583ee0b5443c71d1 (chore: make expect timeout field required in the protocol (https://github.com/microsoft/playwright/pull/33309))
  - [x] https://github.com/microsoft/playwright/commit/0221f15f4ff84f18d9d95f0a9ce71b39cdc9e1a6 (chore(control-or-meta): mention in docs (https://github.com/microsoft/playwright/pull/33338))
  - [x] https://github.com/microsoft/playwright/commit/9ce401d44a81bf2a0947364f10453506d459ff86 (chore: suggest aria snapshots w/ regex (https://github.com/microsoft/playwright/pull/33334))
  - [x] https://github.com/microsoft/playwright/commit/135ed28740fdac3cf28dd4c1829fa60b00c3fc0d (chore: more yaml escaping tests (https://github.com/microsoft/playwright/pull/33387))
  - [x] https://github.com/microsoft/playwright/commit/8b49d568de6f51373b8f1b1e1961ca71a1439598 (docs: start adding the aria snapshot documentation (https://github.com/microsoft/playwright/pull/33407))
  - [x] https://github.com/microsoft/playwright/commit/fa10bcd5a30c94c1a966bc34ab33b8b214dbf47a (feat(tracing) Adding groups to trace via pw-api (https://github.com/microsoft/playwright/pull/33081))
  - [x] https://github.com/microsoft/playwright/commit/9b2ca93a507f3598f8c546bcc3ff56bb1d4d3619 (chore: followup to tracing.group (https://github.com/microsoft/playwright/pull/33450))
  - [x] https://github.com/microsoft/playwright/commit/697d7a40b1d92a2bc45c37f992d9d3c69a1faf68 (fix(routeWebSocket): make it work with http(s) baseURL (https://github.com/microsoft/playwright/pull/33457))
  - [x] https://github.com/microsoft/playwright/commit/a655b0bfb34bb18e5c0321af9a7d87bb64b6e116 (chrome: aria api review (https://github.com/microsoft/playwright/pull/33458))
  - [x] https://github.com/microsoft/playwright/commit/50775698ae13642742f2a1e8983d1d686d7f192d (fix: parent step for API calls inside waitForEvent callback (https://github.com/microsoft/playwright/pull/33409))
  - [x] https://github.com/microsoft/playwright/commit/67e8defbe95f1e4288feae9707b3be2c80ebc0a5 (docs: update tracing.group docs (https://github.com/microsoft/playwright/pull/33487))
  - [x] https://github.com/microsoft/playwright/commit/b021b58379455832775d02949e6a3a07c9af62e7 (chore: allow editing aria template in recorder (https://github.com/microsoft/playwright/pull/33482))
  - [x] https://github.com/microsoft/playwright/commit/c29f57324361f352599db433e7a4b501658a0030 (fix(aria snapshot): assorted fixes (https://github.com/microsoft/playwright/pull/33512))
  - [x] https://github.com/microsoft/playwright/commit/503f74da9089cff4425840a5b297ed5a62a8c15b (chore: allow editing aria template in recorder (tests) (https://github.com/microsoft/playwright/pull/33522))
  - [x] https://github.com/microsoft/playwright/commit/d8a98a2bf52fa579af58ef7cce4a8a56a267c425 (test: fix flaky page.pause() tests end up stalling (https://github.com/microsoft/playwright/pull/33544))
  - [x] https://github.com/microsoft/playwright/commit/099dd80806589ae163854533812d3bb28343732e (fix(recorder): align apiName with the real one (https://github.com/microsoft/playwright/pull/33567))
